import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"; 
import Navbar from "./components/Navbar";       
import BodyWrapper from "./components/BodyWrapper"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Photo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          <BodyWrapper>
            <div className="min-h-screen bg-gray-50" style={{ paddingTop: '64px' }}>
              {children}
            </div>
          </BodyWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}